/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	QueryFunction,
	QueryKey,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { CurrenciesDto } from "./models";
import { authInstance } from "../../instances/authInstance";
import type { ErrorType } from "../../instances/authInstance";

export const currencyControllerFindAll = (signal?: AbortSignal) => {
	return authInstance<CurrenciesDto[]>({ url: `/api/currency`, method: "GET", signal });
};

export const getCurrencyControllerFindAllQueryKey = () => {
	return [`/api/currency`] as const;
};

export const getCurrencyControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof currencyControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof currencyControllerFindAll>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getCurrencyControllerFindAllQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof currencyControllerFindAll>>> = ({
		signal,
	}) => currencyControllerFindAll(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof currencyControllerFindAll>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type CurrencyControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof currencyControllerFindAll>>
>;
export type CurrencyControllerFindAllQueryError = ErrorType<unknown>;

export const useCurrencyControllerFindAll = <
	TData = Awaited<ReturnType<typeof currencyControllerFindAll>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof currencyControllerFindAll>>, TError, TData>
	>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const queryOptions = getCurrencyControllerFindAllQueryOptions(options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
};
