/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface CompanyDto {
	/** @nullable */
	address: string | null;
	/** @nullable */
	city: string | null;
	/** @nullable */
	country: string | null;
	createdAt: string;
	id: string;
	isExist: boolean;
	name: string;
	/** @nullable */
	phone: string | null;
	/** @nullable */
	state: string | null;
	/** @nullable */
	updatedAt: string | null;
	/** @nullable */
	vat: string | null;
	/** @nullable */
	zip: string | null;
}
