/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { CreateProductDtoType } from "./createProductDtoType";

export interface CreateProductDto {
	/** @nullable */
	description?: string | null;
	hsnCode_id: string;
	name: string;
	price: number;
	tax_id: string;
	type: CreateProductDtoType;
	unit_id: string;
	user_id: string;
}
