/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { OmitCreateQuotationProductsDto } from "./omitCreateQuotationProductsDto";

export interface CreateQuotationWithProducts {
	customer_id: string;
	date: string;
	/** @nullable */
	discountPercentage?: number | null;
	expiry_at: string;
	/** @nullable */
	notes?: string | null;
	/** @nullable */
	private_notes?: string | null;
	quatation_number: string;
	quotation: OmitCreateQuotationProductsDto[];
	/** @nullable */
	reference_number?: string | null;
	sub_total: number;
	/** @nullable */
	tax_id?: string | null;
	total: number;
	user_id: string;
}
