/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { BillingAddressDto } from "./billingAddressDto";
import type { GetCustomerWithAddressDtoOption } from "./getCustomerWithAddressDtoOption";
import type { ShippingAddressDto } from "./shippingAddressDto";

export interface GetCustomerWithAddressDto {
	billingAddress?: BillingAddressDto;
	billingAddress_id: string;
	createdAt: string;
	currencies_id: string;
	/** @nullable */
	display_name: string | null;
	/** @nullable */
	email: string | null;
	id: string;
	isExist: boolean;
	name: string;
	option: GetCustomerWithAddressDtoOption;
	/** @nullable */
	phone: string | null;
	shippingAddress?: ShippingAddressDto;
	shippingAddress_id: string;
	/** @nullable */
	updatedAt: string | null;
	user_id: string;
	/** @nullable */
	website: string | null;
}
