/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Customer } from "./customer";
import type { InvoiceWithAllDataDtoPaidStatus } from "./invoiceWithAllDataDtoPaidStatus";
import type { PaymentDetails } from "./paymentDetails";
import type { InvoiceProducts } from "./invoiceProducts";
import type { InvoiceWithAllDataDtoRecurring } from "./invoiceWithAllDataDtoRecurring";
import type { InvoiceWithAllDataDtoTax } from "./invoiceWithAllDataDtoTax";
import type { User } from "./user";

export interface InvoiceWithAllDataDto {
	createdAt: string;
	customer?: Customer;
	customer_id: string;
	date: string;
	/** @nullable */
	discountPercentage: number | null;
	due_date: string;
	id: string;
	invoice_number: string;
	is_recurring: boolean;
	isExist: boolean;
	/** @nullable */
	notes: string | null;
	paid_status: InvoiceWithAllDataDtoPaidStatus;
	payment?: PaymentDetails;
	paymentId: string;
	product?: InvoiceProducts[];
	/** @nullable */
	recurring: InvoiceWithAllDataDtoRecurring;
	/** @nullable */
	reference_number: string | null;
	sub_total: number;
	/** @nullable */
	tax?: InvoiceWithAllDataDtoTax;
	/** @nullable */
	tax_id: string | null;
	total: number;
	/** @nullable */
	updatedAt: string | null;
	user?: User;
	user_id: string;
}
