/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Product } from "./product";
import type { Quotation } from "./quotation";

export interface QuotationProducts {
	createdAt: string;
	/** @nullable */
	hsnCode: number | null;
	id: string;
	isExist: boolean;
	price: number;
	product?: Product;
	product_id: string;
	quantity: number;
	quotation?: Quotation;
	quotation_id: string;
	/** @nullable */
	tax: number | null;
	total: number;
	/** @nullable */
	updatedAt: string | null;
}
