/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */

export interface UpdateCompanyDto {
	/** @nullable */
	address?: string | null;
	/** @nullable */
	city?: string | null;
	/** @nullable */
	country?: string | null;
	name?: string;
	/** @nullable */
	phone?: string | null;
	/** @nullable */
	state?: string | null;
	/** @nullable */
	vat?: string | null;
	/** @nullable */
	zip?: string | null;
}
