/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Growinvoice API
 * Enhance your business with Growinvoice API
 * OpenAPI spec version: 1.0
 */
import type { Currencies } from "./currencies";

/**
 * @nullable
 */
export type UserCurrency = Currencies | null;
